
spring.datasource.url=jdbc:postgresql://rgyjrzkh:GloKeIlUcD48H6TTgKtpMVIc-xyEc3n5@motty.db.elephantsql.com/rgyjrzkh
spring.datasource.username=<YOUR_USERNAME>
spring.datasource.password=<YOUR_PASSWORD>
spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect